### PR TITLE
Financial assistance

### PR DESCRIPTION
**Pull request by callaghanc**
@pierreuno This PR contains a proposal for refactoring how we handle financial assistance data. It moves the financial assistance data from the FinancialAssistanceService down into the data YAML files. It can use a bit more polish but I wanted to get your buy-in to the general idea before putting in the time. We don't have to do it this way - it's possible to keep the data in the FinancialAssistanceService and pull it into the DataService, or to move it into the DataService, etc., but I believe collecting all the data in the YAML files is the cleanest way to go.

### CODE REVIEW

**Comment by pierreuno** [comment]
@callaghanc Now that data is being moved from the NDS API to `config/*.yml` files, it would make sense to have that structure in place for all content. I'm also concerned about time, so use your best judgement as far as prioritizing this implementation.

**Comment by callaghanc** [comment]
roger that @pierreuno, yes it's almost completely ready, the only thing left to do is to update the rendering of the financial assistance items on the provider page so that it does not call the function to fetch the item so many times. should not take much longer, am aware of time constraints so am aiming for minimum functionality to make it work with the new centralized YAML data structure. will do that soon and ping you for review here when it's ready.

**Comment by pierreuno** [comment]
Awesome thanks @callaghanc

**Comment by callaghanc** [comment]
@pierreuno ok this is done, ready for review if you want to

**Pull request merged**
